// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_yN833F1ocjvl7L-ZxMTY3f1ZYFJXAzA',
    appId: '1:1015178862223:web:e8cd5bf9a717bf6419dafa',
    messagingSenderId: '1015178862223',
    projectId: 'nws-flutter-firebase',
    authDomain: 'nws-flutter-firebase.firebaseapp.com',
    storageBucket: 'nws-flutter-firebase.firebasestorage.app',
    measurementId: 'G-P1L85JN0T3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC43g7z4CyrgeFGT7POJFyjc12KxwM7sCI',
    appId: '1:1015178862223:android:5e0066b543620eb519dafa',
    messagingSenderId: '1015178862223',
    projectId: 'nws-flutter-firebase',
    storageBucket: 'nws-flutter-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDJOZssWQPZauiYL_S1OTIJGD1cE0eZa0',
    appId: '1:1015178862223:ios:a5c9c522caaf1ecb19dafa',
    messagingSenderId: '1015178862223',
    projectId: 'nws-flutter-firebase',
    storageBucket: 'nws-flutter-firebase.firebasestorage.app',
    iosBundleId: 'com.example.nws',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDJOZssWQPZauiYL_S1OTIJGD1cE0eZa0',
    appId: '1:1015178862223:ios:a5c9c522caaf1ecb19dafa',
    messagingSenderId: '1015178862223',
    projectId: 'nws-flutter-firebase',
    storageBucket: 'nws-flutter-firebase.firebasestorage.app',
    iosBundleId: 'com.example.nws',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_yN833F1ocjvl7L-ZxMTY3f1ZYFJXAzA',
    appId: '1:1015178862223:web:2f7959029365c28419dafa',
    messagingSenderId: '1015178862223',
    projectId: 'nws-flutter-firebase',
    authDomain: 'nws-flutter-firebase.firebaseapp.com',
    storageBucket: 'nws-flutter-firebase.firebasestorage.app',
    measurementId: 'G-Z2SKJ6LB40',
  );
}
